apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: surua8f11-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/surua8f11-java-quarkus-gitops